import Sidebar from '@/components/Sidebar';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex max-w-screen max-h-screen bg-[#f5f3f3] overflow-hidden">
          <div className="flex flex-col w-64 max-h-screen bg-[#ebebeb] p-4 overflow-y-auto" style={{ scrollbarWidth: "none"}}>
            <Sidebar />
          </div>
          <div className="flex-1 p-4 overflow-y-auto" style={{ scrollbarWidth: "none"}}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
